### ISSUE TITLE
command request: service mapper - map all services

### ISSUE THREAD

**Issue by zoomzoomluke** [Jalle19/tvheadend-helper-scripts#3]
Is there any chance you could add the map all services function please? It's the only function that would be really handy for me to use from the command line.

Many thanks

**Comment by Jalle19** [comment]
Can't you do that from the web interface?

**Comment by zoomzoomluke** [comment]
Yes,

But after automating the import of muxes, channels and doing a scan automatically from the command line it would be good to have a map services command that can be put on a cron job.

**Comment by Jalle19** [comment]
So you're looking to map all services unconditionally, no interactivity required?

**Comment by zoomzoomluke** [comment]
That’s right :)

**Comment by Jalle19** [comment]
Run `git pull` followed by `php composer.phar install` and you should be able to use the service mapper by running `php bin/tvheadend-service-mapper`. See the docs/ directory for details.

**Comment by zoomzoomluke** [comment]
brilliant stuff, thank you very much. can I tip you?

**Comment by Jalle19** [comment]
No need, I just do this for fun. You can star the repository though.
